#
# AthenaSIP - Secure, Minimal, Cloud-Native SIP Server
#
# Copyright (C) 2025 Tom Cully <mail@tomcully.com>
# Licensed under the GNU GPLv3 – see <https://www.gnu.org/licenses/gpl-3.0.html>
#

sip:
  realm: "sip.athenasip.org"
  nonce_secret: "your_nonce_secret_here"
  allow_unencrypted: true

udp:
  enable: true
  address: 0.0.0.0
  port: 5060

tcp:
  enable: true
  address: 0.0.0.0
  port: 5060

tls:
  enable: true
  address: 0.0.0.0
  port: 5061
  cert_pem_filename: "../tls/snakeoil.cer"
  key_pem_filename: "../tls/snakeoil.key"

rtprelay:
  enable: true
  address: 0.0.0.0
  public_address: 0.0.0.0
  port_min: 22000
  port_max: 23000

db:
  url: "mysql://root@localhost/athenasip"

admin_api:
  enable: true
  address: 0.0.0.0
  port: 8080

scripting:
  language: lua     # 'lua' is the default
  add_stdlib: true
  allowed_path: /
  routing_script: ~/.athenasip/routing.lua