//
// AthenaSIP - Secure, Minimal, Cloud-Native SIP Server
//
// Copyright (C) 2026 Tom Cully <mail@tomcully.com>
// Licensed under the GNU GPLv3 – see <https://www.gnu.org/licenses/gpl-3.0.html>
//
#pragma once

#include <cstddef>
#include <functional>
#include <memory>
#include <string>
#include <unordered_map>
#include <vector>

#include "loggers/logger.h"
#include "sip_message.h"
#include "timer_source.h"
#include "types/dialog.h"

namespace athenasip {

// Tracks RFC 3261 section 12 dialogs so the node knows which calls are up: to release
// media, close call records and list live calls. A pure observer: it never routes or
// modifies a message (a proxy is not dialog-stateful, 16.1), and nothing waits on it.
// Strand-confined, like everything Core owns.
class Dialogs : public std::enable_shared_from_this<Dialogs> {
 public:
  using ChangeFn = std::function<void(const std::shared_ptr<types::Dialog>&)>;

  Dialogs(std::shared_ptr<loggers::Logger> logger, std::shared_ptr<TimerSource> timers);

  // A request arriving from the network, before it is processed.
  void observe_request(const std::shared_ptr<SIPMessage>& request);

  // A response going back towards the caller, from a branch or generated by this node, with
  // the request it answers.
  void observe_response(const std::shared_ptr<SIPMessage>& request, const std::shared_ptr<SIPMessage>& response);

  // A fork branch that failed while the fork continues (RFC 3261 16.7). Ends that branch's
  // early dialog, not the attempt; the final response reaches observe_response.
  void observe_branch_failure(const std::shared_ptr<SIPMessage>& request, const std::shared_ptr<SIPMessage>& response);

  // RFC 3261 12.2.2: the dialog a message belongs to, or null.
  std::shared_ptr<types::Dialog> find(const std::shared_ptr<SIPMessage>& message) const;

  // Every live dialog. A terminated one is removed once the change callback has returned.
  std::vector<std::shared_ptr<types::Dialog>> all() const;
  std::size_t size() const;

  // Fires on every state change, including termination.
  void on_change(ChangeFn fn) { _on_change = std::move(fn); }

  // Terminates a dialog that was torn down by other means.
  void terminate(const std::shared_ptr<types::Dialog>& dialog);

 private:
  // The dialogs for one Call-ID. More than one means several fork branches answered (12.1).
  using Branches = std::vector<std::shared_ptr<types::Dialog>>;

  // The dialog for this Call-ID and To tag, created from the caller's half on first sight.
  std::shared_ptr<types::Dialog> _for_tag(const std::string& call_id, const std::string& callee_tag);

  void _changed(const std::shared_ptr<types::Dialog>& dialog);
  void _terminate(const std::shared_ptr<types::Dialog>& dialog, const char* reason);

  // RFC 4028. One timer for the node, set to the earliest session deadline, rather than one
  // per dialog.
  void _reschedule_sweep();
  void _sweep();

  std::shared_ptr<loggers::Logger> _logger;
  std::shared_ptr<TimerSource> _timers;
  ChangeFn _on_change;

  std::shared_ptr<Timer> _sweep_timer;

  std::unordered_map<std::string, Branches> _by_call_id;
};

}  // namespace athenasip
