//
// AthenaSIP - Secure, Minimal, Cloud-Native SIP Server
//
// Copyright (C) 2025 Tom Cully <mail@tomcully.com>
// Licensed under the GNU GPLv3 – see <https://www.gnu.org/licenses/gpl-3.0.html>
//
#include "sip_message.h"

#include "call.h"
#include "channel.h"
#include "headers/cseq_header.h"
#include "headers/via_header.h"
#include "transaction.h"

namespace athenasip {

using namespace athenasip::headers;

// Default constructor
SIPMessage::SIPMessage() {}

std::string SIPMessage::to_string() const {
  std::string out;
  out += header->to_string();
  out += "\r\n";
  if (body.size() != 0) out += body;
  return out;
}

void SIPMessage::print() const { std::cout << Util::trim(to_string()) << std::endl; }

std::string SIPMessage::get_transaction_id() {
  // Transaction ID = transaction_id = topmost_Via.branch + CSeq.method
  auto via = header->headers_map["Via"][0]->as<ViaHeader>();
  auto cseq = header->headers_map["CSeq"][0]->as<CSeqHeader>();

  return via->parameters["branch"] + cseq->method;
}

std::shared_ptr<SIPMessage> SIPMessage::generate_response() {
  // Create Response
  auto response = std::make_shared<SIPMessage>();

  response->header = std::make_shared<SIPHeader>();
  response->header->type = SIPHeader::Type::Response;
  response->body_length = 0;

  // Fields
  response->channel = channel;
  response->contact = contact;
  response->call = call;

  // Add From/To Headers
  if (header->contains("From")) {
    response->header->add("From", header->headers_map["From"][0]);
  } else {
    response->header->add("From", "<sip:unknown@invalid>");
  }

  if (header->contains("To")) {
    response->header->add("To", header->headers_map["To"][0]);
  } else {
    // TODO: Generate random Tag
    response->header->add("To", "<sip:unknown@invalid>;tag=autogen123");
  }

  // Copy Request Headers
  if (header->contains("Call-ID")) {
    response->header->add("Call-ID", header->headers_map["Call-ID"][0]);
  } else {
    // TODO: Generate random Call-ID
    response->header->add("Call-ID", "autogenerated-badreq-1715372000");
  }
  if (header->contains("Via")) response->header->add("Via", header->headers_map["Via"][0]);

  if (header->contains("CSeq")) {
    response->header->add("CSeq", header->headers_map["CSeq"][0]);
  } else {
    // Fabricate a response CSeq
    response->header->add("CSeq", "1 " + header->request_method);
  }

  // Tell the client what is allowed
  response->header->add("Allow", std::make_shared<StringHeader>("INVITE, ACK, CANCEL, OPTIONS, BYE, REFER, NOTIFY, MESSAGE, INFO"));

  return response;
}

std::string operator+(const SIPMessage& message, const std::string& str) { return message.to_string() + str; }
std::string operator+(const std::string& str, const SIPMessage& message) { return str + message.to_string(); }

}  // namespace athenasip
