//
// AthenaSIP - Secure, Minimal, Cloud-Native SIP Server
//
// Copyright (C) 2026 Tom Cully <mail@tomcully.com>
// Licensed under the GNU GPLv3 – see <https://www.gnu.org/licenses/gpl-3.0.html>
//
#include "sip_message.h"

#include "call.h"
#include "channel.h"
#include "headers/cseq_header.h"
#include "headers/sip_identity_header.h"
#include "headers/via_header.h"
#include "util.h"

namespace athenasip {

using namespace athenasip::headers;

// Default constructor
SIPMessage::SIPMessage() {}

std::string SIPMessage::to_string() const {
  std::string out;
  out += header->to_string();
  out += "\r\n";
  if (body.size() != 0) out += body;
  return out;
}

void SIPMessage::print() const { std::cout << Util::trim(to_string()) << std::endl; }

std::string SIPMessage::get_transaction_id() {
  // RFC 3261 17.1.3 and 17.2.3: a transaction is identified by the branch of the
  // topmost Via, the sent-by of that Via and the method. Branch alone collides when
  // two upstream hops happen to pick the same value.
  if (!header->contains("Via") || !header->contains("CSeq")) {
    throw std::runtime_error("SIPMessage::get_transaction_id requires Via and CSeq");
  }

  auto via = header->headers_map["Via"][0]->as<ViaHeader>();
  auto cseq = header->headers_map["CSeq"][0]->as<CSeqHeader>();

  if (via == nullptr || cseq == nullptr) {
    throw std::runtime_error("SIPMessage::get_transaction_id could not read Via or CSeq");
  }

  // The separators matter: without them "abc" + "INVITE" and "abcI" + "NVITE" are the
  // same string.
  return via->parameters["branch"] + "|" + via->host + "|" + cseq->method;
}

// Serialising and re-parsing is the copy. Doing it field by field would mean a virtual
// clone on every header type and a new one every time a type is added; this cannot fall
// behind because it goes through the same writer and reader the wire does.
std::shared_ptr<SIPMessage> SIPMessage::clone() const {
  auto copy = std::make_shared<SIPMessage>();

  copy->header = std::make_shared<SIPHeader>(header->to_string());
  copy->body = body;
  copy->body_length = body_length;

  copy->branch = branch;
  copy->source_port = source_port;
  copy->channel = channel;
  copy->call = call;
  copy->subscriber = subscriber;
  copy->contact = contact;
  copy->authenticated = authenticated;

  return copy;
}

std::shared_ptr<SIPMessage> SIPMessage::generate_response() {
  // Create Response
  auto response = std::make_shared<SIPMessage>();

  response->header = std::make_shared<SIPHeader>();
  response->header->type = SIPHeader::Type::Response;
  response->body_length = 0;

  // Fields
  response->channel = channel;
  response->contact = contact;
  response->call = call;

  // Add From/To Headers
  if (header->contains("From")) {
    response->header->add("From", header->headers_map["From"][0]);
  } else {
    response->header->add("From", "<sip:unknown@invalid>");
  }

  auto to_header = header->contains("To") ? header->headers_map["To"][0]->as<headers::SIPIdentityHeader>() : nullptr;

  if (to_header != nullptr && to_header->value != nullptr) {
    // Copy the identity before touching it. The request's To is shared with this
    // header and is still needed for transaction matching (RFC 3261 17.2.3).
    auto to_identity = std::make_shared<SIPIdentity>(*to_header->value);

    // If the To does not include a tag, add a random one
    if (!to_identity->tags.contains("tag")) {
      to_identity->tags["tag"] = Util::generate_random_string("athena-", 10);
    }

    response->header->add("To", to_identity->to_string());
  } else {
    response->header->add("To", "<sip:unknown@invalid>;tag=" + Util::generate_random_string("athena-", 10));
  }

  // Copy Request Headers
  if (header->contains("Call-ID")) {
    response->header->add("Call-ID", header->headers_map["Call-ID"][0]);
  } else {
    // TODO: Generate random Call-ID
    response->header->add("Call-ID", Util::generate_random_string("autogenerated-badreq-", 10));
  }
  // RFC 3261 8.2.6.2: every Via is copied, in order, or the response cannot retrace
  // the proxy chain it arrived through.
  if (header->contains("Via")) {
    for (const auto& via : header->headers_map["Via"]) response->header->add("Via", via);
  }

  if (header->contains("CSeq")) {
    response->header->add("CSeq", header->headers_map["CSeq"][0]);
  } else {
    // Fabricate a response CSeq
    response->header->add("CSeq", "1 " + header->request_method);
  }

  // Tell the client what is allowed
  response->header->add("Allow", std::make_shared<StringHeader>("INVITE, ACK, CANCEL, OPTIONS, BYE, REFER, NOTIFY, MESSAGE, INFO"));

  return response;
}

std::string operator+(const SIPMessage& message, const std::string& str) { return message.to_string() + str; }
std::string operator+(const std::string& str, const SIPMessage& message) { return str + message.to_string(); }

}  // namespace athenasip
